# frozen_string_literal: true

require "bundler/gem_tasks"
require "rake/testtask"

Rake::TestTask.new do |task|
  task.libs << File.expand_path("lib", __dir__)
  task.pattern = File.expand_path("test/**/*_test.rb", __dir__)
end

task default: :test
